const fs=require('fs');const p='outputs/index.html';let h=fs.readFileSync(p,'utf8');
h=h.replace('<button data-view="timeline">','<button data-view="calendar">▤ 日曆</button><button data-view="timeline">');
// Reorder actual DOM, so keyboard and screen-reader order follows the layout.
const stat='<section class="stats" aria-label="任務統計" id="stats"></section>';
h=h.replace(stat,'');const start=h.indexOf('<section class="tools"'),end=h.indexOf('</section>',start)+10;const tools=h.slice(start,end);h=h.slice(0,start)+h.slice(end);h=h.replace('<main><header>','<main>'+tools+'<div class="workspace"><section class="summary" aria-label="任務總覽"><h2>任務總覽</h2>'+stat+'</section><div class="task-area"><header>');h=h.replace('</p></main></div>','</p></div></div></main></div>');
h=h.replace('</style>',`/* Calendar and left summary */
main{max-width:1450px}.workspace{display:grid;grid-template-columns:190px minmax(0,1fr);gap:26px;align-items:start}.summary{position:sticky;top:20px}.summary h2{font-size:16px;color:#79644f;margin:0 0 16px}.summary .stats{display:grid;grid-template-columns:1fr;gap:12px}.summary .stat{padding:18px 20px}.summary .stat strong{font-size:28px}.task-area{min-width:0}.tools{margin-bottom:28px}nav{flex-wrap:wrap}.calendar-panel{background:#fffdf8;border:1px solid var(--line);border-radius:16px;padding:20px}.calendar-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px;flex-wrap:wrap}.calendar-toolbar h3{margin:0;font-size:20px}.calendar-toolbar div{display:flex;gap:7px}.calendar-week,.calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr))}.calendar-week span{text-align:center;padding:10px;color:#79644f;font-size:14px}.calendar-grid{gap:4px}.calendar-day{min-height:100px;padding:8px;text-align:left;border-radius:9px;background:#fffcf7;display:flex;flex-direction:column;gap:6px;border:1px solid #eee4d7;overflow:hidden}.calendar-day.outside{background:#f5f0e8;color:#8b7c69}.calendar-day.today .date-number{background:#a74720;color:white;border-radius:50%;width:27px;height:27px;display:inline-flex;align-items:center;justify-content:center}.calendar-day.selected{border:2px solid #a74720;background:#f8e8d9}.date-number{font-weight:600;font-size:14px;min-height:27px}.calendar-event{display:block;border-left:3px solid var(--group);background:#f4ece1;padding:3px 5px;border-radius:4px;font-size:12px;color:#5b4939;width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.calendar-more{font-size:12px;color:#79644f}.day-tasks{margin-top:24px}.day-tasks h3{font-size:18px}.calendar-caption{font-size:14px;color:#79644f;line-height:1.7;margin:16px 0 0}
@media(max-width:950px){.workspace{grid-template-columns:160px minmax(0,1fr);gap:18px}.calendar-day{min-height:84px;padding:5px}.calendar-event{font-size:12px}}
@media(max-width:700px){.workspace{grid-template-columns:1fr}.summary{position:static}.summary .stats{grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.summary .stat{padding:13px 10px}.summary .stat strong{font-size:24px}.summary h2{margin-bottom:10px}.calendar-panel{padding:10px}.calendar-day{min-height:74px;padding:4px;gap:3px}.calendar-event{display:none}.calendar-more{font-size:12px}.calendar-day .calendar-mobile-count{display:block}.calendar-toolbar h3{font-size:18px}.calendar-toolbar button{font-size:14px;padding:7px 10px}.calendar-week span{padding:10px 0;font-size:13px}}
@media(min-width:701px){.calendar-mobile-count{display:none}}
</style>`);
h=h.replace("let tasks=[],view='list',selected=null,pendingDelete=null,timer;","let tasks=[],view='list',selected=null,pendingDelete=null,timer;\nlet calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),calendarSelected=null;");
h=h.replace("matrix:'任務優先矩陣',archive:","matrix:'任務優先矩陣',calendar:'任務日曆',archive:");
h=h.replace("if(!rows.length){$('#content')","if(view==='calendar'){renderCalendar(rows);return}\nif(!rows.length){$('#content')");
const calendar=`
function renderCalendar(rows){
 const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());const today=day(new Date());let cells='';
 for(let i=0;i<42;i++){const date=new Date(start.getFullYear(),start.getMonth(),start.getDate()+i),key=day(date),items=rows.filter(t=>day(t.due)===key).sort((a,b)=>new Date(a.due)-new Date(b.due));
 cells+=\`<button class="calendar-day \${date.getMonth()!==month?'outside':''} \${key===today?'today':''} \${key===calendarSelected?'selected':''}" data-calendar-date="\${key}" aria-pressed="\${key===calendarSelected}" aria-label="\${year}年\${date.getMonth()+1}月\${date.getDate()}日，\${items.length}項任務"><span class="date-number">\${date.getDate()}</span>\${items.slice(0,2).map(t=>\`<span class="calendar-event" style="--group:\${groups[t.group][1]}">\${esc(t.title)}</span>\`).join('')}\${items.length>2?'<span class="calendar-more">另 '+(items.length-2)+' 項</span>':''}\${items.length?'<span class="calendar-mobile-count">'+items.length+' 項</span>':''}</button>\`;
 }
 const selectedRows=calendarSelected?rows.filter(t=>day(t.due)===calendarSelected).sort((a,b)=>new Date(a.due)-new Date(b.due)):[];
 $('#content').innerHTML=\`<div class="calendar-panel"><div class="calendar-toolbar"><h3 aria-live="polite">\${year} 年 \${month+1} 月</h3><div><button data-calendar-nav="prev" aria-label="上一個月">上個月</button><button data-calendar-nav="today">本月</button><button data-calendar-nav="next" aria-label="下一個月">下個月</button></div></div><div class="calendar-week">\${['日','一','二','三','四','五','六'].map(d=>'<span>'+d+'</span>').join('')}</div><div class="calendar-grid">\${cells}</div><p class="calendar-caption">以截止日期顯示任務，套用上方搜尋與篩選。點選日期查看任務；已結案任務請至結案紀錄查看。</p></div><section class="day-tasks"><h3>\${calendarSelected?calendarSelected+' 的任務':'選擇日期查看任務'}</h3>\${calendarSelected?(selectedRows.length?'<div class="cards">'+selectedRows.map(card).join('')+'</div>':'<div class="empty">這一天沒有符合條件的任務。</div>'):''}</section>\`;
}
document.addEventListener('click',e=>{const dateButton=e.target.closest('[data-calendar-date]');if(dateButton){calendarSelected=dateButton.dataset.calendarDate;render();const current=document.querySelector('[data-calendar-date="'+calendarSelected+'"]');if(current)current.focus()}const monthButton=e.target.closest('[data-calendar-nav]');if(monthButton){const action=monthButton.dataset.calendarNav;calendarMonth=action==='today'?new Date(new Date().getFullYear(),new Date().getMonth(),1):new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+(action==='next'?1:-1),1);calendarSelected=null;render();document.querySelector('[data-calendar-nav="'+action+'"]').focus()}});
`;
h=h.replace('function edit(id){',calendar+'\nfunction edit(id){');fs.writeFileSync(p,h,'utf8');console.log('Calendar and layout updated');
